version: '3'
services:
  proxy2:
    container_name: proxy2
    hostname: proxy2
    image: nginx:1.19
    # networks:
    # - site1
    # - site2
    ports:
    - '8080:80'
    #- '443:443'

    volumes:
      - ./nginx:/etc/nginx
      - ./ssl:/etc/ssl/private

# networks:
#   site1:
#     external:
#       name: webservice1_default
#   site2:
#     external:
#       name: webservice2_default