version: '2'
services:

  #web:
  #  image: php:8.0.0RC5-apache
  #  ports: 
  #    - "80:80"

  #  volumes:
  #    - ~/docker/bitnami/moodle/www:/var/www/html

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=pk515601
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=pk515601
      
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    container_name: moodle

    environment:
      - MOODLE_USERNAME=cajina
      - MOODLE_PASSWORD=pk515601
      - MOODLE_EMAIL=cajina@gmail.com
      - MARIADB_HOST= db
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=pk515601
      - ALLOW_EMPTY_PASSWORD= "no"
      - MOODLE_SITE_NAME="Capacitaciones Villamar"

    ports:
      - '80:8080'
      - '443:8443'

    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'

    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  #xampp-data:
    #driver: local